# Generated by Django 6.0.6 on 2026-06-17 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField(default="With more than five years of experience in design, i focus on branding, web design, and user experience, i truly enjoy working with businesses that aim to stand out and present their best image. Let's build something incredible together!")),
                ('moon_icon', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('lego_icon', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('object_icon_1', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('object_icon_2', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Settings',
                'verbose_name_plural': 'About Settings',
            },
        ),
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Abdelrhaman', max_length=100)),
                ('role_description', models.TextField(default='a 3d creator driven by crafting striking and unforgettable projects')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Hero Settings',
                'verbose_name_plural': 'Hero Settings',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. 01, 02', max_length=10)),
                ('category', models.CharField(help_text='e.g. Client, Personal', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('live_link', models.URLField(blank=True, max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube/Vimeo/Direct video URL', max_length=500, null=True)),
                ('video_file', models.FileField(blank=True, help_text='Alternatively, upload a video file', null=True, upload_to='projects/videos/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. 01, 02', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
